spring:
  application:
    name: RaizesNordeste
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/db_raizes_nordeste?sslmode=disable
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

gateway:
  pagamento:
    mock:
      url: "https://api.mocki.io/v2/didt58mc"

logging:
  file:
    name: "raizes-nordeste.log"